ASP.NetLab6/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ASP.NetLab6.Models
{
    public class Department
    {
        [Key]
        public int DeptId { get; set; }
        public string Name { get; set; }

        public virtual List<Student> Students { get; set; }
        public virtual List<Course> Courses { get; set; }
    }
}

ASP.NetLab6/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP.NetLab6.Models;

namespace ASP.NetLab6.Controllers
{
    public class DepartmentController : Controller
    {
        ASPModel1 db = new ASPModel1();
        // GET: Department
        public ActionResult Index()
        {
            return View(db.Departments);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Department dept)
        {
            db.Departments.Add(dept);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Post(int id)
        {
            Department dept = db.Departments.Find(id);
            return View(dept);
        }

        [HttpPost]
        public ActionResult Post(Department d, int id)
        {
            if (ModelState.IsValid)
            {
                Department dept = db.Departments.Find(id);
                dept.Name = d.Name;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(d);
        }

        public ActionResult Delete(int id)
        {
            Department dept = db.Departments.Find(id);
            db.Departments.Remove(dept);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ASP.NetLab6/Views/Department/Create.cshtml
@model Department
@{
    ViewBag.title = "Dept Create";
}

    <div class="container">
        <div class="row">
            <div class="col">
                <form action="/Department/Create" method="post">
                    <div class="form-group">
                        @Html.LabelFor(d => d.Name, new { @for = "Name" })
                        @Html.TextBoxFor(d => d.Name, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

ASP.NetLab6/Views/Department/Index.cshtml
@model IEnumerable<Department>
@{
    ViewBag.title = "Depts Home";
}

    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Dept ID</th>
                            <th>Dept Name</th>
                            <th>Edit/Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Any() == false)
                        {
                            <tr>
                                <td colspan="2" class="bg-red">Table is Empty</td>
                            </tr>
                        }
                        else
                        {

                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.DeptId</td>
                                    <td>@item.Name</td>
                                    <td>@Html.ActionLink("Edit", "Post", "Department", new { id = item.DeptId }, new { @class = "btn btn-info" }) / @Html.ActionLink("Delete", "Delete", "Department", new { id = item.DeptId }, new { @class = "btn btn-danger" })</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
            <div class="col-12">
                @Html.ActionLink("Add Dept", "Create", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>

ASP.NetLab6/Views/Department/Post.cshtml
@model Department
@{
    ViewBag.title = "Depts Edit";
}
<div class="container">
    <div class="row">
        <div class="col">
            <form action="/Department/Post/@Model.DeptId" method="post">
                <div class="form-group">
                    @Html.LabelFor(d => d.Name, new { @for = "Name" })
                    @Html.TextBoxFor(d => d.Name, new { @class = "form-control", value = Model.Name })
                </div>
                <button type="submit" class="btn btn-primary">Edit</button>
            </form>
        </div>
    </div>
</div>