ASP.NetLab6/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ASP.NetLab6.Models
{
    public class Course
    {
        public int CourseId { get; set; }
        [Required]
        public string CourseName { get; set; }
        [Range(5,100)]
        public int Duration{ get; set; }
        public virtual List<Department> Departments { get; set; }
    }
}

ASP.NetLab6/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP.NetLab6.Models;

namespace ASP.NetLab6.Controllers
{
    public class CourseController : Controller
    {
        ASPModel1 db = new ASPModel1();
        // GET: Course
        public ActionResult Index()
        {
            return View(db.Courses);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Course c)
        {
            if(ModelState.IsValid)
            {
                db.Courses.Add(c);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public ActionResult Post(int id)
        {
            Course c = db.Courses.Find(id);
            return View(c);
        }

        [HttpPost]
        public ActionResult Post(Course c, int id)
        {
            if(ModelState.IsValid)
            {
                Course cr = db.Courses.Find(id);
                cr.CourseName = c.CourseName;
                cr.Duration = c.Duration;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(c);
        }

        public ActionResult Delete(int id)
        {
            Course c = db.Courses.Find(id);
            db.Courses.Remove(c);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ASP.NetLab6/Views/Course/Create.cshtml
@model Course
@{
    ViewBag.title = "Course Create";
}
<div class="container">
    <div class="row">
        <div class="col">
            <form action="/Course/Create" method="post">
                <div class="form-group">
                    @Html.LabelFor(c => c.CourseName, new { @for = "CourseName" })
                    @Html.TextBoxFor(c => c.CourseName, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(c => c.Duration, new { @for = "Duration" })
                    @Html.TextBoxFor(c => c.Duration, new { @class = "form-control" })
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

ASP.NetLab6/Views/Course/Index.cshtml
@model IEnumerable<Course>
@{
    ViewBag.title = "Course Home";
}
<div class="container">
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Course ID</th>
                        <th>Course Name</th>
                        <th>Course Duration</th>
                        <th>Edit/Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Any() == false)
                    {
                        <tr>
                            <td colspan="2" class="bg-red">Table is Empty</td>
                        </tr>
                    }
                    else
                    {

                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.CourseId</td>
                                <td>@item.CourseName</td>
                                <td>@item.Duration</td>
                                <td>@Html.ActionLink("Edit", "Post", "Course", new { id = item.CourseId }, new { @class = "btn btn-info" }) / @Html.ActionLink("Delete", "Delete", "Course", new { id = item.CourseId }, new { @class = "btn btn-danger" })</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <div class="col-12">
            @Html.ActionLink("Add Course", "Create", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>

ASP.NetLab6/Views/Course/Post.cshtml
@model Course
@{
    ViewBag.title = "Course Edit";
}
<div class="container">
    <div class="row">
        <div class="col">
            <form action="/Course/Post/@Model.CourseId" method="post">
                <div class="form-group">
                    @Html.LabelFor(c => c.CourseName, new { @for = "CourseName" })
                    @Html.TextBoxFor(c => c.CourseName, new { @class = "form-control", value = Model.CourseName })
                </div>
                <div class="form-group">
                    @Html.LabelFor(c => c.Duration, new { @for = "Duration" })
                    @Html.TextBoxFor(c => c.Duration, new { @class = "form-control", value = Model.Duration })
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
</div>